export const carList = [
  {
    id: "01",
    make: "Renault",
    model: "Clio",
    year: "2007",
    engineSize: 1.2,
    bhp: 89,
    doors: "2",
    miles: 120000,
    ownerAmount: 7,
    price: 4000,
    username: "dreamMechanic",
    pictureFilenames: ["Car1.jpg"],
  },
  {
    id: "02",
    make: "Toyota",
    model: "Corolla",
    year: "1995",
    engineSize: 1.0,
    bhp: 120,
    doors: "2",
    miles: 50000,
    ownerAmount: 2,
    price: 15000,
    username: "drivingsavvy23",
    pictureFilenames: ["Car2.jpg"],
  },
  {
    id: "03",
    make: "Honda",
    model: "Civic",
    year: "2002",
    engineSize: 2.0,
    bhp: 160,
    doors: "4",
    miles: 40000,
    ownerAmount: 1,
    price: 17000,
    username: "autoLover87",
    pictureFilenames: ["Car3.jpg"],
  },
  {
    id: "04",
    make: "Ford",
    model: "Mustang",
    year: "2004",
    engineSize: 5.0,
    bhp: 296,
    doors: "2",
    miles: 30000,
    ownerAmount: 3,
    price: 25000,
    username: "speedyRider",
    pictureFilenames: ["Car4.jpg"],
  },
  {
    id: "05",
    make: "Chevrolet",
    model: "Malibu",
    year: "2000",
    engineSize: 2.0,
    bhp: 20,
    doors: "4",
    miles: 55000,
    ownerAmount: 2,
    price: 18000,
    username: "carfanatic99",
    pictureFilenames: ["Car5.jpg"],
  },
  {
    id: "06",
    make: "BMW",
    model: "3 Series",
    year: "2013",
    engineSize: 3.0,
    bhp: 150,
    doors: "4",
    miles: 60000,
    ownerAmount: 1,
    price: 30000,
    username: "luxuryRider",
    pictureFilenames: ["Car6.jpg"],
  },
  {
    id: "07",
    make: "Mercedes-Benz",
    model: "C-Class",
    year: "2015",
    engineSize: 1.2,
    bhp: 113,
    doors: "4",
    miles: 35000,
    ownerAmount: 2,
    price: 28000,
    username: "smoothDriver",
    pictureFilenames: ["Car7.jpg"],
  },
  {
    id: "08",
    make: "Audi",
    model: "A4",
    year: "2007",
    engineSize: 2.0,
    bhp: 170,
    doors: "4",
    miles: 45000,
    owners: 2,
    price: 26000,
    username: "sleekMachine",
    pictureFilenames: ["Car8.jpg"],
  },
  {
    id: "09",
    make: "Nissan",
    model: "Altima",
    year: "2020",
    engineSize: 1.6,
    bhp: 120,
    doors: "4",
    miles: 48000,
    ownerAmount: 1,
    price: 16000,
    username: "roadmaster",
    pictureFilenames: ["Car9.jpg"],
  },
  {
    id: "10",
    make: "Hyundai",
    model: "Elantra",
    year: "2010",
    engineSize: 2.0,
    bhp: 200,
    doors: "4",
    miles: 32000,
    ownerAmount: 1,
    price: 14000,
    username: "cruiser88",
    pictureFilenames: ["Car10.jpg"],
  },
  {
    id: "11",
    make: "Volkswagen",
    model: "Jetta",
    year: "2017",
    engineSize: 1.9,
    bhp: 120,
    doors: "4",
    miles: 42000,
    ownerAmount: 2,
    price: 19000,
    username: "vwlover",
    pictureFilenames: ["Car11.jpg"],
  },
  {
    id: "12",
    make: "Ford",
    model: "focus",
    year: "2020",
    engineSize: 1.0,
    bhp: 113,
    doors: "5",
    miles: 70000,
    ownerAmount: 1,
    price: 10000,
    username: "speedyRider",
    pictureFilenames: ["Car12.jpg"],
  },
];
