export const initialData = [
  {
    id: "01",
    make: "Renault",
    model: "Clio",
    miles: 120000,
    ownerAmount: 7,
    price: 4000,
    user: "dreamMechanic",
    pictureFilenames: ["Car1.jpg"],
  },
  {
    id: "02",
    make: "Toyota",
    model: "Corolla",
    miles: 50000,
    owners: 2,
    price: 15000,
    username: "drivingsavvy23",
    pictureFilenames: ["Car2.jpg"],
  },
  {
    id: "03",
    make: "Honda",
    model: "Civic",
    miles: 40000,
    owners: 1,
    price: 17000,
    username: "autoLover87",
    pictureFilenames: ["Car3.jpg"],
  },
  {
    id: "04",
    make: "Ford",
    model: "Mustang",
    miles: 30000,
    owners: 3,
    price: 25000,
    username: "speedyRider",
    pictureFilenames: ["Car4.jpg"],
  },
  {
    id: "05",
    make: "Chevrolet",
    model: "Malibu",
    miles: 55000,
    owners: 2,
    price: 18000,
    username: "carfanatic99",
    pictureFilenames: ["Car5.jpg"],
  },
  {
    id: "06",
    make: "BMW",
    model: "3 Series",
    miles: 60000,
    owners: 1,
    price: 30000,
    username: "luxuryRider",
    pictureFilenames: ["Car6.jpg"],
  },
  {
    id: "07",
    make: "Mercedes-Benz",
    model: "C-Class",
    miles: 35000,
    owners: 2,
    price: 28000,
    username: "smoothDriver",
    pictureFilenames: ["Car7.jpg"],
  },
  {
    id: "08",
    make: "Audi",
    model: "A4",
    miles: 45000,
    owners: 2,
    price: 26000,
    username: "sleekMachine",
    pictureFilenames: ["Car8.jpg"],
  },
  {
    id: "09",
    make: "Nissan",
    model: "Altima",
    miles: 48000,
    owners: 1,
    price: 16000,
    username: "roadmaster",
    pictureFilenames: ["Car9.jpg"],
  },
  {
    id: "10",
    make: "Hyundai",
    model: "Elantra",
    miles: 32000,
    owners: 1,
    price: 14000,
    username: "cruiser88",
    pictureFilenames: ["Car10.jpg"],
  },
  {
    id: "11",
    make: "Volkswagen",
    model: "Jetta",
    miles: 42000,
    owners: 2,
    price: 19000,
    username: "vwlover",
    pictureFilenames: ["Car11.jpg"],
  },
  {
    id: "12",
    make: "Ford",
    model: "focus",
    miles: 70000,
    owners: 1,
    price: 10000,
    username: "speedyRider",
    pictureFilenames: ["Car4.jpg"],
  },
];
