export const data = [
  {
    make: "make 1",
    model: "",
    miles: 0,
    ownerAmount: 0,
    price: 0,
    user: "User 1 ",
    pictureFilenames: ["car1.jpg"],
    id: "01",
  },
  {
    make: "make 2",
    model: "",
    miles: 0,
    ownerAmount: 0,
    price: 0,
    user: "User 2",
    pictureFilenames: ["car2.jpg"],
    id: "02",
  },
  {
    make: "make 3",
    model: "",
    miles: 0,
    ownerAmount: 0,
    price: 0,
    user: "User 3",
    pictureFilenames: ["car2.jpg"],
    id: "03",
  },
  {
    make: "make 4",
    model: "",
    miles: 0,
    ownerAmount: 0,
    price: 0,
    user: "User 4",
    pictureFilenames: ["car2.jpg"],
    id: "04",
  },
  {
    make: "make 5",
    model: "",
    miles: 0,
    ownerAmount: 0,
    price: 0,
    user: "User 5",
    pictureFilenames: ["car2.jpg"],
    id: "05",
  },
  {
    make: "make 6",
    model: "",
    miles: 0,
    ownerAmount: 0,
    price: 0,
    user: "User 6",
    pictureFilenames: ["car2.jpg"],
    id: "06",
  },
  {
    make: "make 7",
    model: "",
    miles: 0,
    ownerAmount: 0,
    price: 0,
    user: "User 7",
    pictureFilenames: ["car2.jpg"],
    id: "07",
  },
  {
    make: "make 8",
    model: "",
    miles: 0,
    ownerAmount: 0,
    price: 0,
    user: "User 8",
    pictureFilenames: ["car2.jpg"],
    id: "08",
  },
  {
    make: "make 9",
    model: "",
    miles: 0,
    ownerAmount: 0,
    price: 0,
    user: "User 9",
    pictureFilenames: ["car2.jpg"],
    id: "09",
  },
];
